#pragma once
// Auto-generated by 'bb8 upload' before each flash - do not edit.
// These defaults appear only for builds made outside bb8 (e.g. Arduino IDE).
#define BB8_BUILD_NUM  0
#define BB8_BUILD_DATE "unstamped"
#define BB8_BUILD_GIT  "none"
