<#
.SYNOPSIS  Build a self-contained Z-Class Control System release bundle.
.DESCRIPTION
  1. Stamps every RC4 sketch (versions.json +1, date, git hash) and compiles all four.
  2. Publishes bb8 as a self-contained single-file win-x64 exe (no .NET runtime needed).
  3. Assembles: bb8\, firmware\ (sources), binaries\<target>\ (prebuilt), docs\ (+ .docx
     renders via Word if available), tools\ (release scripts, Bb8Commander source,
     step_tree.py), targets.json, versions.json, README, Install-ZClass.ps1 at the root.
  4. Zips to dist\ZClass-ControlSystem-v<Version>.zip.  -Publish creates the GitHub
     release (tag v<Version>) with the zip + per-board binaries attached.
.EXAMPLE   .\tools\release\make-release.ps1 -Version 1.01
           git add -A firmware versions.json; git commit -m "release v1.01"; git tag v1.01; git push --tags
           .\tools\release\make-release.ps1 -Version 1.01 -Publish -SkipBuild
#>
param(
  [Parameter(Mandatory)][string]$Version,
  [switch]$Publish,
  [switch]$SkipBuild,
  [switch]$SkipDocx
)
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "..\..")).Path
Set-Location $Root
$Stage = Join-Path $Root "dist\stage\ZClass-ControlSystem-v$Version"
$Zip   = Join-Path $Root "dist\ZClass-ControlSystem-v$Version.zip"
$cfg   = Get-Content "targets.json" -Raw | ConvertFrom-Json
$git   = (git rev-parse --short HEAD).Trim()
if ($null -ne (git status --porcelain -- firmware tools/Bb8Commander targets.json)) { $git += "+" }

if (-not $SkipBuild) {
  # ---- 1. stamp + compile ----
  Write-Host "`n[1/4] stamp + compile (git $git)" -ForegroundColor Yellow
  $ver = Get-Content "versions.json" -Raw | ConvertFrom-Json
  $date = Get-Date -Format "yyyy-MM-dd HH:mm"
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $n = [int]$ver.($t.name) + 1
    $ver.($t.name) = $n
    $hdr = Join-Path $cfg.sketchRoot "$($t.sketch)\BuildStamp.h"
    @"
#pragma once
// Auto-generated by tools/release/make-release.ps1 (release v$Version) - do not edit.
#define BB8_BUILD_NUM  $n
#define BB8_BUILD_DATE "$date"
#define BB8_BUILD_GIT  "$git"
"@ | Set-Content $hdr -Encoding ascii
    (Get-Item (Join-Path $cfg.sketchRoot "$($t.sketch)\$($t.sketch).ino")).LastWriteTimeUtc = [DateTime]::UtcNow
    Write-Host "  $($t.name): build $n"
  }
  $ver | ConvertTo-Json | Set-Content "versions.json" -Encoding ascii
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    Write-Host "  compiling $($t.name) ($($t.fqbn))..."
    & arduino-cli compile --fqbn $t.fqbn --build-path (Join-Path $cfg.buildRoot $t.sketch) (Join-Path $cfg.sketchRoot $t.sketch) | Select-String "Sketch uses"
    if ($LASTEXITCODE -ne 0) { throw "compile failed: $($t.name)" }
  }

  # ---- 2. bb8 self-contained ----
  Write-Host "[2/4] bb8 self-contained publish" -ForegroundColor Yellow
  if (Test-Path $Stage) { Remove-Item $Stage -Recurse -Force }
  New-Item -ItemType Directory -Force (Join-Path $Stage "bb8") | Out-Null
  dotnet publish "tools\Bb8Commander" -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none `
    -o (Join-Path $Stage "bb8") --nologo -v quiet
  if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed" }
}

# ---- 3. assemble ----
Write-Host "[3/4] assemble $Stage" -ForegroundColor Yellow
New-Item -ItemType Directory -Force $Stage | Out-Null
foreach ($d in @("firmware", "docs")) { Copy-Item (Join-Path $Root $d) $Stage -Recurse -Force }
New-Item -ItemType Directory -Force (Join-Path $Stage "tools") | Out-Null
$bbSrc = Join-Path $Root "tools\Bb8Commander"; $bbDst = Join-Path $Stage "tools\Bb8Commander"
if (Test-Path $bbDst) { cmd /c rd /s /q "$bbDst" }
robocopy $bbSrc $bbDst /E /XD bin obj /NFL /NDL /NJH /NJS /NP | Out-Null   # source only, no build junk
Copy-Item "tools\release" (Join-Path $Stage "tools") -Recurse -Force
Copy-Item "tools\step_tree.py" (Join-Path $Stage "tools")
foreach ($f in @("targets.json", "versions.json", "README.md", "install.ps1")) { Copy-Item $f $Stage -Force }
Copy-Item "tools\release\Install-ZClass.ps1" $Stage -Force            # installer at the root
foreach ($t in $cfg.targets) {                                          # prebuilt binaries
  if ($t.name -eq "ball") { continue }
  $src = Join-Path $cfg.buildRoot $t.sketch
  $dst = Join-Path $Stage "binaries\$($t.name)"
  New-Item -ItemType Directory -Force $dst | Out-Null
  Get-ChildItem $src -File | Where-Object { $_.Extension -in ".bin", ".hex" } | Copy-Item -Destination $dst
}
Set-Content (Join-Path $Stage "VERSION") "Z-Class Control System v$Version`nbuilt $(Get-Date -Format s) from git $git`nboards: $((Get-Content versions.json -Raw) -replace '\s+',' ')" -Encoding ascii
# release notes = top CHANGELOG section + quick start
$chg = Get-Content "docs\CHANGELOG.md" -Raw
$top = ($chg -split "(?m)^## ")[1]
@"
# Z-Class Control System v$Version

## Install — step by step (Windows, no admin needed)

**1. Download** ``ZClass-ControlSystem-Setup-v$Version.exe`` (below) and run it.
   The installer is unsigned, so SmartScreen may say *"Windows protected your PC"* → click **More info → Run anyway**.

**2. Choose the install folder.** Default ``%LOCALAPPDATA%\ZClass``. Any folder you can write to is fine — the toolchain and your builds live inside it.

**3. Tick the first-run tasks:**
   - ☑ **Install arduino-cli + board cores + libraries now** — needs internet, about 10 minutes. Required before you can compile or flash (re-runnable later from the Start menu → *Re-run toolchain setup*).
   - ☑ **Link the install folder to GitHub** — needs ``git`` installed. Lets ``bb8 update`` pull new firmware from this repo from then on.
   - Desktop shortcut — optional.

**4. Let the PowerShell window finish.** It opens automatically after the files copy and runs what you ticked; wait for ``=== Ready ===``.

**5. Open a NEW terminal** (PATH just changed) and check:
``````
bb8 list
``````
You should see the five targets (drive, dome, ball, body, imu) and any boards on USB.

**6. First session**
| Do | Command |
|---|---|
| pair PS3 / Nav pads | ``bb8 pair`` |
| flash a board (compile from source + verify) | ``bb8 upload drive``  (then ``body``, ``imu``, ``dome``) |
| flash the bundled prebuilt binaries instead | ``tools\release\Flash-Prebuilt.ps1 -Target drive -Port COM4`` |
| watch a board / the drive through the dome | ``bb8 monitor drive`` / ``bb8 monitor ball`` |
| read | Start menu → *How-To Guide*, or the [wiki](https://github.com/jlvandusen/Z-ClassControlSystem/wiki) |

**Uninstall:** Start menu → *Z-Class Control System → Uninstall*.

*Prefer no installer?* ``ZClass-ControlSystem-v$Version.zip`` is the same bundle — extract, then ``.\Install-ZClass.ps1``. The ``firmware-<board>-v$Version.zip`` assets are just the binaries.

## What's in this release
## $top
"@ | Set-Content (Join-Path $Stage "RELEASE_NOTES.md") -Encoding UTF8

# docx renders (Word COM) - optional
if (-not $SkipDocx) {
  try {
    $w = New-Object -ComObject Word.Application; $w.Visible = $false
    $dx = Join-Path $Stage "docs\docx"; New-Item -ItemType Directory -Force $dx | Out-Null
    foreach ($name in @("HowToGuide", "Assembly_Drive", "RigTuning", "Runbook", "CHANGELOG")) {
      $html = Join-Path $env:TEMP "$name.html"
      python "tools\release\md2html.py" "docs\$name.md" $html "$name" | Out-Null
      $doc = $w.Documents.Open($html, $false, $true)
      $doc.SaveAs2((Join-Path $dx "$name.docx"), 16); $doc.Close($false)
      Write-Host "  docx: $name"
    }
    $w.Quit()
  } catch { Write-Host "  (docx skipped: $($_.Exception.Message))" -ForegroundColor DarkYellow }
}

# ---- 4. zip (+ publish) ----
Write-Host "[4/4] zip" -ForegroundColor Yellow
if (Test-Path $Zip) { Remove-Item $Zip -Force }
Compress-Archive -Path $Stage -DestinationPath $Zip -CompressionLevel Optimal
Write-Host "  $Zip  ($([math]::Round((Get-Item $Zip).Length/1MB,1)) MB)" -ForegroundColor Green

# ---- 5. Setup.exe (Inno Setup, if installed) ----
$SetupExe = Join-Path $Root "dist\ZClass-ControlSystem-Setup-v$Version.exe"
$iscc = Get-ChildItem "${env:ProgramFiles(x86)}\Inno Setup*\ISCC.exe", "$env:ProgramFiles\Inno Setup*\ISCC.exe", "$env:LOCALAPPDATA\Programs\Inno Setup*\ISCC.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($iscc) {
  Write-Host "[5/5] Setup.exe (Inno Setup)" -ForegroundColor Yellow
  & $iscc.FullName /Q "/DVersion=$Version" "/DStage=$Stage" "/DOut=$(Join-Path $Root 'dist')" (Join-Path $Root "tools\release\ZClass.iss")
  if ($LASTEXITCODE -ne 0) { throw "ISCC failed" }
  Write-Host "  $SetupExe  ($([math]::Round((Get-Item $SetupExe).Length/1MB,1)) MB)" -ForegroundColor Green
} else { Write-Host "[5/5] Inno Setup not found - no Setup.exe (zip only)" -ForegroundColor DarkYellow }

if ($Publish) {
  Write-Host "publishing GitHub release v$Version" -ForegroundColor Yellow
  $assets = @($Zip)
  if (Test-Path $SetupExe) { $assets += $SetupExe }
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $b = Join-Path $Stage "binaries\$($t.name)"
    $bz = Join-Path $Root "dist\firmware-$($t.name)-v$Version.zip"
    if (Test-Path $bz) { Remove-Item $bz -Force }
    Compress-Archive -Path "$b\*" -DestinationPath $bz; $assets += $bz
  }
  gh release create "v$Version" --title "Z-Class Control System v$Version" --notes-file (Join-Path $Stage "RELEASE_NOTES.md") @assets
}
Write-Host "done." -ForegroundColor Green
