<#
.SYNOPSIS  Build a self-contained Z-Class Control System release bundle.
.DESCRIPTION
  1. Stamps every RC4 sketch (versions.json +1, date, git hash) and compiles all four.
  2. Publishes bb8 as a self-contained single-file win-x64 exe (no .NET runtime needed).
  3. Assembles: bb8\, firmware\ (sources), binaries\<target>\ (prebuilt), docs\ (+ .docx
     renders via Word if available), tools\ (release scripts, Bb8Commander source,
     step_tree.py), targets.json, versions.json, README, Install-ZClass.ps1 at the root.
  4. Zips to dist\ZClass-ControlSystem-v<Version>.zip.  -Publish creates the GitHub
     release (tag v<Version>) with the zip + per-board binaries attached.
.EXAMPLE   .\tools\release\make-release.ps1 -Version 1.01
           git add -A firmware versions.json; git commit -m "release v1.01"; git tag v1.01; git push --tags
           .\tools\release\make-release.ps1 -Version 1.01 -Publish -SkipBuild
#>
param(
  [Parameter(Mandatory)][string]$Version,
  [switch]$Publish,
  [switch]$SkipBuild,
  [switch]$SkipDocx
)
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "..\..")).Path
Set-Location $Root
$Stage = Join-Path $Root "dist\stage\ZClass-ControlSystem-v$Version"
$Zip   = Join-Path $Root "dist\ZClass-ControlSystem-v$Version.zip"
$cfg   = Get-Content "targets.json" -Raw | ConvertFrom-Json
$git   = (git rev-parse --short HEAD).Trim()
if ((git status --porcelain -- firmware tools/Bb8Commander targets.json) -ne $null) { $git += "+" }

if (-not $SkipBuild) {
  # ---- 1. stamp + compile ----
  Write-Host "`n[1/4] stamp + compile (git $git)" -ForegroundColor Yellow
  $ver = Get-Content "versions.json" -Raw | ConvertFrom-Json
  $date = Get-Date -Format "yyyy-MM-dd HH:mm"
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $n = [int]$ver.($t.name) + 1
    $ver.($t.name) = $n
    $hdr = Join-Path $cfg.sketchRoot "$($t.sketch)\BuildStamp.h"
    @"
#pragma once
// Auto-generated by tools/release/make-release.ps1 (release v$Version) - do not edit.
#define BB8_BUILD_NUM  $n
#define BB8_BUILD_DATE "$date"
#define BB8_BUILD_GIT  "$git"
"@ | Set-Content $hdr -Encoding ascii
    (Get-Item (Join-Path $cfg.sketchRoot "$($t.sketch)\$($t.sketch).ino")).LastWriteTimeUtc = [DateTime]::UtcNow
    Write-Host "  $($t.name): build $n"
  }
  $ver | ConvertTo-Json | Set-Content "versions.json" -Encoding ascii
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    Write-Host "  compiling $($t.name) ($($t.fqbn))..."
    & arduino-cli compile --fqbn $t.fqbn --build-path (Join-Path $cfg.buildRoot $t.sketch) (Join-Path $cfg.sketchRoot $t.sketch) | Select-String "Sketch uses"
    if ($LASTEXITCODE -ne 0) { throw "compile failed: $($t.name)" }
  }

  # ---- 2. bb8 self-contained ----
  Write-Host "[2/4] bb8 self-contained publish" -ForegroundColor Yellow
  if (Test-Path $Stage) { Remove-Item $Stage -Recurse -Force }
  New-Item -ItemType Directory -Force (Join-Path $Stage "bb8") | Out-Null
  dotnet publish "tools\Bb8Commander" -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none `
    -o (Join-Path $Stage "bb8") --nologo -v quiet
  if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed" }
}

# ---- 3. assemble ----
Write-Host "[3/4] assemble $Stage" -ForegroundColor Yellow
New-Item -ItemType Directory -Force $Stage | Out-Null
foreach ($d in @("firmware", "docs")) { Copy-Item (Join-Path $Root $d) $Stage -Recurse -Force }
New-Item -ItemType Directory -Force (Join-Path $Stage "tools") | Out-Null
$bbSrc = Join-Path $Root "tools\Bb8Commander"; $bbDst = Join-Path $Stage "tools\Bb8Commander"
if (Test-Path $bbDst) { cmd /c rd /s /q "$bbDst" }
robocopy $bbSrc $bbDst /E /XD bin obj /NFL /NDL /NJH /NJS /NP | Out-Null   # source only, no build junk
Copy-Item "tools\release" (Join-Path $Stage "tools") -Recurse -Force
Copy-Item "tools\step_tree.py" (Join-Path $Stage "tools")
foreach ($f in @("targets.json", "versions.json", "README.md", "install.ps1")) { Copy-Item $f $Stage -Force }
Copy-Item "tools\release\Install-ZClass.ps1" $Stage -Force            # installer at the root
foreach ($t in $cfg.targets) {                                          # prebuilt binaries
  if ($t.name -eq "ball") { continue }
  $src = Join-Path $cfg.buildRoot $t.sketch
  $dst = Join-Path $Stage "binaries\$($t.name)"
  New-Item -ItemType Directory -Force $dst | Out-Null
  Get-ChildItem $src -File | Where-Object { $_.Extension -in ".bin", ".hex" } | Copy-Item -Destination $dst
}
Set-Content (Join-Path $Stage "VERSION") "Z-Class Control System v$Version`nbuilt $(Get-Date -Format s) from git $git`nboards: $((Get-Content versions.json -Raw) -replace '\s+',' ')" -Encoding ascii
# release notes = top CHANGELOG section + quick start
$chg = Get-Content "docs\CHANGELOG.md" -Raw
$top = ($chg -split "(?m)^## ")[1]
@"
# Z-Class Control System v$Version

## Install (fresh PC)
1. Extract the zip anywhere (e.g. ``C:\ZClass``).
2. PowerShell in that folder: ``.\Install-ZClass.ps1``  - installs arduino-cli + the exact cores/libraries, puts ``bb8`` on PATH, and (if git is present) links the folder to GitHub so ``bb8 update`` keeps it current.
3. New terminal -> ``bb8 list`` -> ``bb8 upload drive`` (body / imu / dome likewise). Prebuilt binaries: ``tools\release\Flash-Prebuilt.ps1 -Target drive -Port COMx``.
4. Read ``docs\HowToGuide.md``.

## What's in this release
## $top
"@ | Set-Content (Join-Path $Stage "RELEASE_NOTES.md") -Encoding UTF8

# docx renders (Word COM) - optional
if (-not $SkipDocx) {
  try {
    $w = New-Object -ComObject Word.Application; $w.Visible = $false
    $dx = Join-Path $Stage "docs\docx"; New-Item -ItemType Directory -Force $dx | Out-Null
    foreach ($name in @("HowToGuide", "Assembly_Drive", "RigTuning", "Runbook", "CHANGELOG")) {
      $html = Join-Path $env:TEMP "$name.html"
      python "tools\release\md2html.py" "docs\$name.md" $html "$name" | Out-Null
      $doc = $w.Documents.Open($html, $false, $true)
      $doc.SaveAs2((Join-Path $dx "$name.docx"), 16); $doc.Close($false)
      Write-Host "  docx: $name"
    }
    $w.Quit()
  } catch { Write-Host "  (docx skipped: $($_.Exception.Message))" -ForegroundColor DarkYellow }
}

# ---- 4. zip (+ publish) ----
Write-Host "[4/4] zip" -ForegroundColor Yellow
if (Test-Path $Zip) { Remove-Item $Zip -Force }
Compress-Archive -Path $Stage -DestinationPath $Zip -CompressionLevel Optimal
Write-Host "  $Zip  ($([math]::Round((Get-Item $Zip).Length/1MB,1)) MB)" -ForegroundColor Green

if ($Publish) {
  Write-Host "publishing GitHub release v$Version" -ForegroundColor Yellow
  $assets = @($Zip)
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $b = Join-Path $Stage "binaries\$($t.name)"
    $bz = Join-Path $Root "dist\firmware-$($t.name)-v$Version.zip"
    if (Test-Path $bz) { Remove-Item $bz -Force }
    Compress-Archive -Path "$b\*" -DestinationPath $bz; $assets += $bz
  }
  gh release create "v$Version" --title "Z-Class Control System v$Version" --notes-file (Join-Path $Stage "RELEASE_NOTES.md") @assets
}
Write-Host "done." -ForegroundColor Green
