<#
.SYNOPSIS  Build a self-contained Z-Class Control System release bundle.
.DESCRIPTION
  1. Stamps every RC4 sketch (versions.json +1, date, git hash) and compiles all four.
  2. Publishes bb8 as a self-contained single-file win-x64 exe (no .NET runtime needed).
  3. Assembles: bb8\, firmware\ (sources), binaries\<target>\ (prebuilt), docs\ (+ .docx
     renders via Word if available), tools\ (release scripts, Bb8Commander source,
     step_tree.py), targets.json, versions.json, README, Install-ZClass.ps1 at the root.
  4. Zips to dist\ZClass-ControlSystem-v<Version>.zip.  -Publish creates the GitHub
     release (tag v<Version>) with the zip + per-board binaries attached.
.EXAMPLE   .\tools\release\make-release.ps1 -Version 1.01
           git add -A firmware versions.json; git commit -m "release v1.01"; git tag v1.01; git push --tags
           .\tools\release\make-release.ps1 -Version 1.01 -Publish -SkipBuild
#>
param(
  [Parameter(Mandatory)][string]$Version,
  [switch]$Publish,
  [switch]$SkipBuild,
  [switch]$SkipDocx
)
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "..\..")).Path
Set-Location $Root
$Stage = Join-Path $Root "dist\stage\ZClass-ControlSystem-v$Version"
$Zip   = Join-Path $Root "dist\ZClass-ControlSystem-v$Version.zip"
$cfg   = Get-Content "targets.json" -Raw | ConvertFrom-Json
$git   = (git rev-parse --short HEAD).Trim()
if ($null -ne (git status --porcelain -- firmware tools/Bb8Commander targets.json)) { $git += "+" }

if (-not $SkipBuild) {
  # ---- 1. stamp + compile ----
  Write-Host "`n[1/4] stamp + compile (git $git)" -ForegroundColor Yellow
  $ver = Get-Content "versions.json" -Raw | ConvertFrom-Json
  $date = Get-Date -Format "yyyy-MM-dd HH:mm"
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $n = [int]$ver.($t.name) + 1
    $ver.($t.name) = $n
    $hdr = Join-Path $cfg.sketchRoot "$($t.sketch)\BuildStamp.h"
    @"
#pragma once
// Auto-generated by tools/release/make-release.ps1 (release v$Version) - do not edit.
#define BB8_BUILD_NUM  $n
#define BB8_BUILD_DATE "$date"
#define BB8_BUILD_GIT  "$git"
"@ | Set-Content $hdr -Encoding ascii
    (Get-Item (Join-Path $cfg.sketchRoot "$($t.sketch)\$($t.sketch).ino")).LastWriteTimeUtc = [DateTime]::UtcNow
    Write-Host "  $($t.name): build $n"
  }
  $ver | ConvertTo-Json | Set-Content "versions.json" -Encoding ascii
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    Write-Host "  compiling $($t.name) ($($t.fqbn))..."
    & arduino-cli compile --fqbn $t.fqbn --build-path (Join-Path $cfg.buildRoot $t.sketch) (Join-Path $cfg.sketchRoot $t.sketch) | Select-String "Sketch uses"
    if ($LASTEXITCODE -ne 0) { throw "compile failed: $($t.name)" }
  }

  # ---- 2. bb8 self-contained ----
  Write-Host "[2/4] bb8 self-contained publish" -ForegroundColor Yellow
  if (Test-Path $Stage) { Remove-Item $Stage -Recurse -Force }
  New-Item -ItemType Directory -Force (Join-Path $Stage "bb8") | Out-Null
  dotnet publish "tools\Bb8Commander" -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none `
    -o (Join-Path $Stage "bb8") --nologo -v quiet
  if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed" }
}

# ---- 3. assemble ----
Write-Host "[3/4] assemble $Stage" -ForegroundColor Yellow
New-Item -ItemType Directory -Force $Stage | Out-Null
foreach ($d in @("firmware", "docs")) { Copy-Item (Join-Path $Root $d) $Stage -Recurse -Force }
New-Item -ItemType Directory -Force (Join-Path $Stage "tools") | Out-Null
$bbSrc = Join-Path $Root "tools\Bb8Commander"; $bbDst = Join-Path $Stage "tools\Bb8Commander"
if (Test-Path $bbDst) { cmd /c rd /s /q "$bbDst" }
robocopy $bbSrc $bbDst /E /XD bin obj /NFL /NDL /NJH /NJS /NP | Out-Null   # source only, no build junk
Copy-Item "tools\release" (Join-Path $Stage "tools") -Recurse -Force
Copy-Item "tools\step_tree.py" (Join-Path $Stage "tools")
foreach ($f in @("targets.json", "versions.json", "README.md", "install.ps1")) { Copy-Item $f $Stage -Force }
Copy-Item "tools\release\Install-ZClass.ps1" $Stage -Force            # installer at the root
# prebuilt binaries + flash.json manifests ('bb8 flash' - flashing without the
# toolchain: bundled esptool for the ESP32s, native AVR109 for the 32u4, UF2
# file-copy for the Trinket M0) + the bundled esptool itself.
$verNow = Get-Content "versions.json" -Raw | ConvertFrom-Json
$arduino15 = Join-Path $env:LOCALAPPDATA "Arduino15\packages"
$esptool = Get-ChildItem (Join-Path $arduino15 "esp32*\tools\esptool_py\*\esptool.exe") -ErrorAction SilentlyContinue |
           Sort-Object FullName -Descending | Select-Object -First 1
if ($esptool) {
  New-Item -ItemType Directory -Force (Join-Path $Stage "tools\flash") | Out-Null
  Copy-Item $esptool.FullName (Join-Path $Stage "tools\flash\esptool.exe") -Force
  Write-Host "  tools\flash\esptool.exe  ($($esptool.Directory.Name))"
} else { Write-Host "  esptool.exe not found in Arduino15 - BASIC ESP32 flashing would need it on PATH" -ForegroundColor DarkYellow }
foreach ($t in $cfg.targets) {
  if ($t.name -eq "ball") { continue }
  $src = Join-Path $cfg.buildRoot $t.sketch
  $dst = Join-Path $Stage "binaries\$($t.name)"
  New-Item -ItemType Directory -Force $dst | Out-Null
  Get-ChildItem $src -File | Where-Object { $_.Extension -in ".bin", ".hex" } | Copy-Item -Destination $dst
  $build = [int]$verNow.($t.name)
  if ($t.fqbn -match ":avr:") {
    $manifest = [ordered]@{ method = "avr109"; build = $build; file = "$($t.sketch).ino.hex" }
  } elseif ($t.fqbn -match ":samd:") {
    $manifest = [ordered]@{ method = "uf2"; build = $build; file = "$($t.sketch).ino.bin"
                            base = "0x2000"; familyId = "0x68ED2B88"; volume = "TRINKETBOOT" }
  } else {
    $core = if ($t.fqbn -like "esp32-bluepad32*") { "esp32-bluepad32" } else { "esp32" }
    $bootApp0 = Get-ChildItem (Join-Path $arduino15 "$core\hardware\esp32\*\tools\partitions\boot_app0.bin") -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $bootApp0) { $bootApp0 = Get-ChildItem (Join-Path $arduino15 "*\hardware\esp32\*\tools\partitions\boot_app0.bin") -ErrorAction SilentlyContinue | Select-Object -First 1 }
    if ($bootApp0) { Copy-Item $bootApp0.FullName (Join-Path $dst "boot_app0.bin") -Force }
    else { Write-Host "  boot_app0.bin not found for $($t.name) - its flash.json will be incomplete" -ForegroundColor DarkYellow }
    $manifest = [ordered]@{ method = "esptool"; build = $build; baud = 921600
                            flashMode = "dio"; flashFreq = "80m"; images = @(
      [ordered]@{ offset = "0x1000";  file = "$($t.sketch).ino.bootloader.bin" },
      [ordered]@{ offset = "0x8000";  file = "$($t.sketch).ino.partitions.bin" },
      [ordered]@{ offset = "0xE000";  file = "boot_app0.bin" },
      [ordered]@{ offset = "0x10000"; file = "$($t.sketch).ino.bin" }
    ) }
  }
  $manifest | ConvertTo-Json -Depth 4 | Set-Content (Join-Path $dst "flash.json") -Encoding ascii
  Write-Host "  binaries\$($t.name): build $build ($($manifest.method))"
}
Set-Content (Join-Path $Stage "VERSION") "Z-Class Control System v$Version`nbuilt $(Get-Date -Format s) from git $git`nboards: $((Get-Content versions.json -Raw) -replace '\s+',' ')" -Encoding ascii
# release notes = top CHANGELOG section + quick start
$chg = Get-Content "docs\CHANGELOG.md" -Raw
$top = ($chg -split "(?m)^## ")[1]
@"
# Z-Class Control System v$Version

## Which download?

| You want to… | Download |
|---|---|
| **Drive the droid** — flash the ready-made firmware, stay updated automatically | ``ZClass-ControlSystem-Setup-BASIC-v$Version.exe`` — **no git, no Arduino toolchain, no compiling.** Flashers are bundled; updates come straight from GitHub Releases. |
| **Modify the firmware** — edit the source and compile it yourself | ``ZClass-ControlSystem-Setup-MAX-v$Version.exe`` — everything in BASIC **plus** the arduino-cli toolchain setup (~1 GB, one time) and the git link for source-level ``bb8 update``. |

Not sure? Take **BASIC** — installing MAX over it later upgrades in place, same folder.

## Install — step by step (Windows, no admin needed)

**1. Download** your Setup exe (above) and run it.
   The installer is unsigned, so SmartScreen may say *"Windows protected your PC"* → click **More info → Run anyway**.

**2. Choose the install folder.** Default ``%LOCALAPPDATA%\ZClass``. Any folder you can write to is fine — everything lives inside it and the folder is fully relocatable.

**3. (MAX only) Tick the first-run tasks:**
   - ☑ **Install arduino-cli + board cores + libraries now** — needs internet, about 10 minutes. Required before you can *compile* (flashing prebuilt firmware never needs it — that's what BASIC does).
   - ☑ **Link the install folder to GitHub** — needs ``git`` installed. Lets ``bb8 update`` pull source commits.
   - Desktop shortcut — optional (BASIC has this one too).

**4. Let the PowerShell window finish.** It opens automatically after the files copy and runs what you ticked; wait for ``=== Ready ===``.

**5. Open a NEW terminal** (PATH just changed) and check:
``````
bb8 list
``````
You should see the five targets (drive, dome, ball, body, imu) and any boards on USB.

**6. First session**
| Do | Command |
|---|---|
| pair PS3 / Nav pads | ``bb8 pair`` |
| flash a board — BASIC: prebuilt binary, no toolchain | ``bb8 flash drive``  (then ``body``, ``imu``, ``dome``) — ``bb8 upload`` does the same automatically when there's no toolchain |
| flash a board — MAX: compile from source + verify | ``bb8 upload drive`` |
| get the next release later | ``bb8 update`` (BASIC pulls the GitHub release over HTTPS; ``--flash`` also reflashes boards that are behind) |
| watch a board / the drive through the dome | ``bb8 monitor drive`` / ``bb8 monitor ball`` |
| **new droid / fresh boards?** | follow [First-Time Setup](https://github.com/jlvandusen/Z-ClassControlSystem/wiki/First-Time-Setup) end to end |
| read | Start menu → *How-To Guide*, or the [wiki](https://github.com/jlvandusen/Z-ClassControlSystem/wiki) |

**Uninstall:** Start menu → *Z-Class Control System → Uninstall*.

*Prefer no installer?* ``ZClass-ControlSystem-v$Version.zip`` is the same bundle — extract, then ``.\Install-ZClass.ps1`` (add ``-SkipToolchain -NoGit`` for a BASIC-style setup). The ``firmware-<board>-v$Version.zip`` assets are just the binaries.

## What's in this release
## $top
"@ | Set-Content (Join-Path $Stage "RELEASE_NOTES.md") -Encoding UTF8

# docx renders (Word COM) - optional
if (-not $SkipDocx) {
  try {
    $w = New-Object -ComObject Word.Application; $w.Visible = $false
    $dx = Join-Path $Stage "docs\docx"; New-Item -ItemType Directory -Force $dx | Out-Null
    foreach ($name in @("FirstTimeSetup", "HowToGuide", "Assembly_Drive", "RigTuning", "Runbook", "CHANGELOG")) {
      $html = Join-Path $env:TEMP "$name.html"
      python "tools\release\md2html.py" "docs\$name.md" $html "$name" | Out-Null
      $doc = $w.Documents.Open($html, $false, $true)
      $doc.SaveAs2((Join-Path $dx "$name.docx"), 16); $doc.Close($false)
      Write-Host "  docx: $name"
    }
    $w.Quit()
  } catch { Write-Host "  (docx skipped: $($_.Exception.Message))" -ForegroundColor DarkYellow }
}

# ---- 4. zip (+ publish) ----
Write-Host "[4/4] zip" -ForegroundColor Yellow
if (Test-Path $Zip) { Remove-Item $Zip -Force }
Compress-Archive -Path $Stage -DestinationPath $Zip -CompressionLevel Optimal
Write-Host "  $Zip  ($([math]::Round((Get-Item $Zip).Length/1MB,1)) MB)" -ForegroundColor Green

# ---- 5. Setup.exe x2: BASIC (prebuilt-flash users) + MAX (source + toolchain) ----
$SetupExes = @("BASIC", "MAX") | ForEach-Object { Join-Path $Root "dist\ZClass-ControlSystem-Setup-$_-v$Version.exe" }
$iscc = Get-ChildItem "${env:ProgramFiles(x86)}\Inno Setup*\ISCC.exe", "$env:ProgramFiles\Inno Setup*\ISCC.exe", "$env:LOCALAPPDATA\Programs\Inno Setup*\ISCC.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($iscc) {
  Write-Host "[5/5] Setup.exe (Inno Setup, BASIC + MAX)" -ForegroundColor Yellow
  foreach ($flavor in @("BASIC", "MAX")) {
    & $iscc.FullName /Q "/DVersion=$Version" "/DStage=$Stage" "/DOut=$(Join-Path $Root 'dist')" "/DFlavor=$flavor" (Join-Path $Root "tools\release\ZClass.iss")
    if ($LASTEXITCODE -ne 0) { throw "ISCC failed ($flavor)" }
    $exe = Join-Path $Root "dist\ZClass-ControlSystem-Setup-$flavor-v$Version.exe"
    Write-Host "  $exe  ($([math]::Round((Get-Item $exe).Length/1MB,1)) MB)" -ForegroundColor Green
  }
} else { Write-Host "[5/5] Inno Setup not found - no Setup.exe (zip only)" -ForegroundColor DarkYellow }

if ($Publish) {
  Write-Host "publishing GitHub release v$Version" -ForegroundColor Yellow
  $assets = @($Zip)
  foreach ($e in $SetupExes) { if (Test-Path $e) { $assets += $e } }
  foreach ($t in $cfg.targets) {
    if ($t.name -eq "ball") { continue }
    $b = Join-Path $Stage "binaries\$($t.name)"
    $bz = Join-Path $Root "dist\firmware-$($t.name)-v$Version.zip"
    if (Test-Path $bz) { Remove-Item $bz -Force }
    Compress-Archive -Path "$b\*" -DestinationPath $bz; $assets += $bz
  }
  # SHA256SUMS asset — bb8's release-channel update verifies its download against it
  $sums = Join-Path $Root "dist\SHA256SUMS-v$Version.txt"
  $assets | ForEach-Object { "{0}  {1}" -f (Get-FileHash $_ -Algorithm SHA256).Hash.ToLower(), (Split-Path $_ -Leaf) } |
    Set-Content $sums -Encoding ascii
  $assets += $sums
  gh release create "v$Version" --title "Z-Class Control System v$Version" --notes-file (Join-Path $Stage "RELEASE_NOTES.md") @assets
}
Write-Host "done." -ForegroundColor Green
