"""
Z-Class v10 mainboard — single source of truth for the KiCad generator.

Each component: ref, value, kind (symbol shape), footprint spec, placement (KiCad mm,
origin = axle centre, +x toward the tail, +y up), and pins: (number, name, net).
Net naming: power rails start with '+', 'GND' is ground, 'NC' = no-connect.
"""

# ---------------------------------------------------------------- modules
DEVKIT_LEFT  = ["EN","VP","VN","D34","D35","D32","D33","D25","D26","D27","D14","D12","D13","GND","VIN"]
DEVKIT_RIGHT = ["D23","D22","TX0","RX0","D21","D19","D18","D5","TX2","RX2","D4","D2","D15","GND","3V3"]  # top=antenna end, bottom=USB end
DEVKIT_NETS = {
    "EN":"NC", "VP":"ESTOP_SENSE", "VN":"NC", "D34":"S2S_POS", "D35":"VBAT_SENSE",
    "D32":"FLY_PWM", "D33":"FLY_INA", "D25":"S2S_PWM", "D26":"S2S_INA", "D27":"S2S_INB",
    "D14":"FLY_INB", "D12":"NC", "D13":"I2C_A_SDA", "GND":"GND", "VIN":"+5V_LOGIC",
    "3V3":"NC", "D15":"I2C_A_SCL", "D2":"NC", "D4":"DRIVE_PWM", "RX2":"DRIVE_INA", "TX2":"DRIVE_INB",
    "D5":"NC", "D18":"NC", "D19":"NC", "D21":"LINK_ESP_TX", "RX0":"NC", "TX0":"NC",
    "D22":"LINK_RP_TX", "D23":"NC",
}
ZERO_LEFT   = ["5V","GND","3V3","GP29","GP28","GP27","GP26","GP15","GP14"]
ZERO_RIGHT  = ["GP0","GP1","GP2","GP3","GP4","GP5","GP6","GP7","GP8"]
ZERO_END    = ["GP9","GP10","GP11","GP12","GP13"]
ZERO_NETS = {
    "5V":"RP_5V", "GND":"GND", "3V3":"NC", "GP29":"NC", "GP28":"V5_SENSE", "GP27":"I2C_B_SCL",
    "GP26":"I2C_B_SDA", "GP15":"DF_BUSY", "GP14":"NEO_3V3",
    "GP0":"LINK_RP_TX", "GP1":"LINK_ESP_TX", "GP2":"AMP_SHDN", "GP3":"NC", "GP4":"DF_TX_RP", "GP5":"DF_RX_RP",
    "GP6":"SERVO_L", "GP7":"SERVO_R", "GP8":"DOME_PWM",
    "GP9":"DOME_INA", "GP10":"DOME_INB", "GP11":"ENC_A_3V3", "GP12":"ENC_B_3V3", "GP13":"HALL",
}
DFPLAYER = [  # pin, name, net  (2x8, pin 1 top-left, counter-clockwise like the module)
    (1,"VCC","+5V_LOGIC"), (2,"RX","DF_RX_MOD"), (3,"TX","DF_RX_RP"), (4,"DAC_R","DF_DAC_R"), (5,"DAC_L","DF_DAC_L"),
    (6,"SPK2","NC"), (7,"GND","GND"), (8,"SPK1","NC"), (9,"IO1","NC"), (10,"GND","GND"), (11,"IO2","NC"),
    (12,"ADKEY1","NC"), (13,"ADKEY2","NC"), (14,"USB+","NC"), (15,"USB-","NC"), (16,"BUSY","DF_BUSY"),
]
# Amp as a plug-in module header for rev A (MAX9744 board); rev B integrates the QFN.
AMP_HDR = [(1,"VDD12","AMP_12V"),(2,"GND","GND"),(3,"INL","AMP_INL"),(4,"INR","AMP_INR"),(5,"AGND","GND"),
           (6,"SDA","I2C_B_SDA"),(7,"SCL","I2C_B_SCL"),(8,"SHDN","AMP_SHDN"),
           (9,"OUTL+","SPK_L+"),(10,"OUTL-","SPK_L-"),(11,"OUTR+","SPK_R+"),(12,"OUTR-","SPK_R-"),
           (13,"VI2C","+3V3"),(14,"GND","GND")]   # Vi2c: the module's I2C level-shifter reference - REQUIRED (3.3 V)

def pins_devkit():
    p = []
    for i, n in enumerate(DEVKIT_LEFT, 1):  p.append((i, n, DEVKIT_NETS[n]))
    for i, n in enumerate(DEVKIT_RIGHT, 16): p.append((i, n, DEVKIT_NETS[n]))
    return p

def pins_zero():
    p = []
    for i, n in enumerate(ZERO_LEFT, 1):    p.append((i, n, ZERO_NETS[n]))
    for i, n in enumerate(ZERO_RIGHT, 10):  p.append((i, n, ZERO_NETS[n]))
    for i, n in enumerate(ZERO_END, 19):    p.append((i, n, ZERO_NETS[n]))
    return p

def two(ref, value, kind, fp, at, n1, n2, side="F", rot=0):
    return dict(ref=ref, value=value, kind=kind, fp=fp, at=at, rot=rot, side=side,
                pins=[(1, "1", n1), (2, "2", n2)])

COMPONENTS = []
A = COMPONENTS.append

# ---- MCU modules (custom footprints generated by the tool)
# U1 ESP32 DevKitC (30-pin) and U2 RP2350-Zero are CUSTOMER-FITTED modules that plug into socket
# headers. The sockets are the board parts (assembled by the fab); pad positions equal the old
# single-footprint module pads, so routing is unchanged. kind=connector, fixed=True (placer never moves them).
#   ESP32 left row  pins 1..15  at x = 37-12.7, pin 1 at y = +17.78 running DOWN (KiCad +y)
#   ESP32 right row pins 16..30 at x = 37+12.7
SOCKET_1x15 = "Connector_PinSocket_2.54mm:PinSocket_1x15_P2.54mm_Vertical"
SOCKET_1x09 = "Connector_PinSocket_2.54mm:PinSocket_1x09_P2.54mm_Vertical"
SOCKET_1x05 = "Connector_PinSocket_2.54mm:PinSocket_1x05_P2.54mm_Vertical"
_dk = pins_devkit(); _zr = pins_zero()
A(dict(ref="J_U1A", value="ESP32 DevKitC socket L (1x15)", kind="connector", fp=SOCKET_1x15, fixed=True,
       at=(37 - 12.7, 17.78), rot=0, side="F", pins=[(i + 1, n, net) for i, (num, n, net) in enumerate(_dk[:15])]))
A(dict(ref="J_U1B", value="ESP32 DevKitC socket R (1x15)", kind="connector", fp=SOCKET_1x15, fixed=True,
       at=(37 + 12.7, 17.78), rot=0, side="F", pins=[(i + 1, n, net) for i, (num, n, net) in enumerate(_dk[15:30])]))
#   RP2350-Zero: left row pins 1..9 at x=-10-7.62 from y = 33+11.43 down; right row pins 10..18 at x=-10+7.62;
#   end row pins 19..23 along +x at y = 33-10.16, pin 19 at x = -10-5.08
A(dict(ref="J_U2A", value="RP2350-Zero socket L (1x9)", kind="connector", fp=SOCKET_1x09, fixed=True,
       at=(-10 - 7.62, 33 + 11.43), rot=0, side="F", pins=[(i + 1, n, net) for i, (num, n, net) in enumerate(_zr[:9])]))
A(dict(ref="J_U2B", value="RP2350-Zero socket R (1x9)", kind="connector", fp=SOCKET_1x09, fixed=True,
       at=(-10 + 7.62, 33 + 11.43), rot=0, side="F", pins=[(i + 1, n, net) for i, (num, n, net) in enumerate(_zr[9:18])]))
A(dict(ref="J_U2C", value="RP2350-Zero socket end (1x5)", kind="connector", fp=SOCKET_1x05, fixed=True,
       at=(-10 - 5.08, 33 - 10.16), rot=90, side="F", pins=[(i + 1, n, net) for i, (num, n, net) in enumerate(_zr[18:23])]))
# DFPlayer at the tail with rot=0 so the SD slot (footprint local +X) faces the
# board's right/outward edge — card is inserted/removed from the tail opening.
A(dict(ref="U3", value="DFPlayer Mini", kind="module", fp="ZCLASS:DFPlayer_2x8",
       at=(78, -18), rot=0, side="F", pins=DFPLAYER))
A(dict(ref="J_AMP", value="MAX9744 amp module hdr", kind="connector", fp="Connector_PinHeader_2.54mm:PinHeader_2x07_P2.54mm_Vertical",
       at=(-28, 30), rot=0, side="F", pins=AMP_HDR))
# ---- power modules
# Pololu step-downs: real pin row is EN VIN GND GND OUT (5 x 0.1 in). EN left open = enabled
# (100k pull-up on the module). Both GND pins are bonded on the module - tie both.
A(dict(ref="PS1", value="Pololu D24V50F5 5V 5A", kind="module", fp="ZCLASS:Pololu_D24V50F5",
       at=(-30, 4), rot=0, side="F", pins=[(1,"EN","NC"),(2,"VIN","VIN"),(3,"GND","GND"),(4,"GND","GND"),(5,"VOUT","+5V_LOGIC")]))
A(dict(ref="PS2", value="Pololu D24V25F6 6V 2.5A", kind="module", fp="ZCLASS:Pololu_D24V25F6",
       at=(-34, -20), rot=90, side="F", pins=[(1,"EN","NC"),(2,"VIN","VIN"),(3,"GND","GND"),(4,"GND","GND"),(5,"VOUT","+6V_SERVO")]))
A(dict(ref="U5", value="AP7361C-33 3.3V LDO", kind="ic3", fp="Package_TO_SOT_SMD:SOT-223-3_TabPin2",
       at=(18, -28), rot=0, side="F", pins=[(1,"GND","GND"),(2,"VOUT","+3V3"),(3,"VIN","+5V_LOGIC")]))
# ---- protection / input
A(dict(ref="J1", value="XT60PB-M vertical", kind="connector", fp="Connector_AMASS:AMASS_XT60-M_1x02_P7.20mm_Vertical",
       at=(-27, -31), rot=0, side="F", pins=[(1,"+","BAT+"),(2,"-","GND")]))
A(dict(ref="F1", value="10A blade fuse", kind="fuse", fp="ZCLASS:Fuse_Mini_Blade",
       at=(-13, -26.5), rot=0, side="F", pins=[(1,"1","BAT+"),(2,"2","BAT_F")]))
# High-side reverse-polarity P-FET. PowerPAK SO-8 pinout: pads 1,2,3 = SOURCE, 4 = GATE,
# 5 = DRAIN (tab). RPP orientation: D = battery side (BAT_F), S = load side (VIN);
# body diode pre-charges VIN, then VGS = -VIN enhances; a reversed pack is blocked.
# Si7461DP: -60 V, 14.5 mOhm, -14 A (SQJ431EP was 213 mOhm and an SO-8L part - wrong).
A(dict(ref="Q1", value="Si7461DP P-FET RPP", kind="ic3", fp="Package_SO:PowerPAK_SO-8_Single",
       at=(-1, -26), rot=0, side="F",
       pins=[(1,"S","VIN"),(2,"S","VIN"),(3,"S","VIN"),(4,"G","Q1_G"),(5,"D","BAT_F")]))
# gate protection: VGS clamped to -12 V (abs max +/-20 V; SMBJ15A can let VIN reach ~24 V)
A(two("D6", "BZT52C12 12V zener", "diode", "Diode_SMD:D_SOD-123", (-1, -22), "VIN", "Q1_G"))   # pin1 K = VIN (source), pin2 A = gate
A(two("R33", "47k", "res", "Resistor_SMD:R_0603_1608Metric", (3, -22), "Q1_G", "GND"))
A(two("D1", "SMBJ15A", "diode", "Diode_SMD:D_SMB", (8, -22.5), "VIN", "GND"))
A(two("C1", "220u/25V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-32, -19), "VIN", "GND"))
A(two("R24", "47k", "res", "Resistor_SMD:R_0603_1608Metric", (44, 44), "VIN", "VBAT_SENSE"))
A(two("R25", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (44, 41), "VBAT_SENSE", "GND"))
# ADC protection (GPIO35 is input-only, no internal clamps): BAT54S series pair in SOT-23,
# pin1 = A1 -> GND, pin2 = K2 -> +3V3, pin3 = common -> sense node. Plus 100n (SAR ADC charge reservoir).
A(dict(ref="D4", value="BAT54S", kind="ic3", fp="Package_TO_SOT_SMD:SOT-23", at=(47, 38), rot=0, side="F",
       pins=[(1,"A1","GND"),(2,"K2","+3V3"),(3,"COM","VBAT_SENSE")]))
A(two("C29", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (44, 37), "VBAT_SENSE", "GND"))
# ---- 5V / 3V3 rail parts
A(two("C2", "470u/10V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-26, -19), "+5V_LOGIC", "GND"))
A(two("C3", "1000u/10V", "cap", "Capacitor_SMD:CP_Elec_10x10", (-22, -20), "+5V_LED", "GND"))
A(two("F3", "3A polyfuse", "fuse", "Fuse:Fuse_1812_4532Metric", (-44, -18), "+5V_LOGIC", "+5V_LED"))
A(two("C4", "470u/16V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-20, -20), "+6V_SERVO", "GND"))
# KiCad D_SMA pad1 = CATHODE. Conducts +5V_LOGIC -> RP_5V, blocks the Zero's USB-C back-feed.
A(two("D2", "SS14", "diode", "Diode_SMD:D_SMA", (0, 48), "RP_5V", "+5V_LOGIC"))
A(two("C5", "10u", "cap", "Capacitor_SMD:C_1206_3216Metric", (-1, -30.8), "+5V_LOGIC", "GND"))
A(two("C6", "10u", "cap", "Capacitor_SMD:C_1206_3216Metric", (24, -31), "+3V3", "GND"))
A(two("R29", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (22, 48), "+5V_LOGIC", "V5_SENSE"))
A(two("R30", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (25, 48), "V5_SENSE", "GND"))
# ---- amp supply
A(two("F4", "3A fuse", "fuse", "Fuse:Fuse_1206_3216Metric", (56, 24), "VIN", "AMP_12V_F"))
A(two("L1", "FB 600R 3A", "res", "Inductor_SMD:L_1206_3216Metric", (60, 24), "AMP_12V_F", "AMP_12V"))
A(two("C7", "1000u/25V", "cap", "Capacitor_SMD:CP_Elec_10x10", (62, 14), "AMP_12V", "GND"))
A(two("C26", "1u", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, -12), "DF_DAC_L", "AMP_INL"))
A(two("C27", "1u", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, -15), "DF_DAC_R", "AMP_INR"))
# ---- motor driver headers (bare unshrouded 2x5, NOT keyed — mark pin 1 on the ribbons):
#      odd pins = channel A: VCC PWM INA INB GND / even pins = channel B: VCC PWM INA INB GND
def motor_hdr(ref, at, chA, chB):
    pa, ia, ib = chA; pb, ja, jb = chB
    return dict(ref=ref, value="DFR0601 ribbon 2x5", kind="connector", fp="Connector_PinHeader_2.54mm:PinHeader_2x05_P2.54mm_Vertical",
                at=at, rot=0, side="F",
                pins=[(1,"VCC","+3V3"),(3,"PWM1",pa),(5,"INA1",ia),(7,"INB1",ib),(9,"GND","GND"),
                      (2,"VCC","+3V3"),(4,"PWM2",pb),(6,"INA2",ja),(8,"INB2",jb),(10,"GND","GND")])
A(motor_hdr("J2", (-8, -41), ("DRIVE_PWM","DRIVE_INA","DRIVE_INB"), ("S2S_PWM","S2S_INA","S2S_INB")))
A(motor_hdr("J3", (13, -41),  ("FLY_PWM","FLY_INA","FLY_INB"),     ("DOME_PWM","DOME_INA","DOME_INB")))
# pull-downs on every driver input
for i, net in enumerate(["DRIVE_PWM","DRIVE_INA","DRIVE_INB","S2S_PWM","S2S_INA","S2S_INB",
                         "FLY_PWM","FLY_INA","FLY_INB","DOME_PWM","DOME_INA","DOME_INB"]):
    A(two(f"R{12+i}", "10k", "res", "Resistor_SMD:R_0603_1608Metric", ((-17 + i*3) if i < 6 else (4 + (i-6)*3), -33.5), net, "GND"))
# ---- servos: 6.0 V rail = the one voltage both the Hitec HS-805BB (4.8-6.0 V) and the
#      JX PDI-HV2060MG (6.0-8.4 V) accept. Both are jumbo (1/4-scale) cases.
A(dict(ref="J4", value="Servo L", kind="connector", fp="Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical",
       at=(55, 21), rot=0, side="F", pins=[(1,"SIG","SERVO_L"),(2,"6V","+6V_SERVO"),(3,"GND","GND")]))
A(dict(ref="J5", value="Servo R", kind="connector", fp="Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical",
       at=(66, 19), rot=0, side="F", pins=[(1,"SIG","SERVO_R"),(2,"6V","+6V_SERVO"),(3,"GND","GND")]))
# ---- IMU (I2C, 4-pin JST-XH like v9.15)
# IMU: GY-BMI160 breakout over I2C (ESP32 I2C-A bus, shared with the AS5600 - addr 0x68/0x69 vs 0x36).
# JST-XH 4-pin in the SAME order as the v9.15 "MPU" connector: VCC GND sig sig -> the old cable fits.
# Pin 1 = +5V into the breakout's VIN (its own LDO makes 3.3 V; SCL/SDA are 3.3 V logic via its pull-ups).
# CS / SA0 left open -> I2C mode. The ESP32 SPI pins (D5/D18/D19/D23) are now spare.
A(dict(ref="J6", value="IMU BMI160 I2C", kind="connector", fp="Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical",
       at=(57, -24), rot=0, side="F",
       pins=[(1,"5V","+5V_LOGIC"),(2,"GND","GND"),(3,"SCL","I2C_A_SCL"),(4,"SDA","I2C_A_SDA")]))
# ---- S2S sensor (AS5600 or pot): 3V3 GND OUT SDA SCL
A(dict(ref="J7", value="S2S AS5600/pot", kind="connector", fp="Connector_JST:JST_XH_B5B-XH-A_1x05_P2.50mm_Vertical",
       at=(70, -19), rot=0, side="F",
       pins=[(1,"3V3","+3V3"),(2,"GND","GND"),(3,"OUT","S2S_OUT"),(4,"SDA","I2C_A_SDA"),(5,"SCL","I2C_A_SCL")]))
A(two("R2", "1k", "res", "Resistor_SMD:R_0603_1608Metric", (64, -30), "S2S_OUT", "S2S_POS"))
A(two("C28", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (67, -30), "S2S_POS", "GND"))
# ---- dome encoder (5V) -> 74LVC245 -> 3V3
#   pin order kept IDENTICAL to the v9.15 DOME_ENC header (B, A, GND, VCC) so the
#   existing NeveRest encoder cable plugs straight in — do not reorder.
A(dict(ref="J8", value="Dome encoder", kind="connector", fp="Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical",
       at=(82, -14), rot=0, side="F", pins=[(1,"B","ENC_B_5V"),(2,"A","ENC_A_5V"),(3,"GND","GND"),(4,"5V","+5V_LOGIC")]))
A(dict(ref="U7", value="74LVC245A", kind="ic_generic", fp="Package_SO:TSSOP-20_4.4x6.5mm_P0.65mm",
       at=(30, -32), rot=0, side="F",
       # DIR HIGH = A->B (TI SN74LVC245A pin table). Encoder 5V sits on A1/A2, RP2350 on B1/B2, so DIR
       # must be +3V3 — it was GND (B->A) on the first rev-A gerbers (r6); fixed in r7. Unused A3..A8
       # are inputs when DIR=H, so they are tied to GND rather than left floating.
       pins=[(1,"DIR","+3V3"),(2,"A1","ENC_A_5V"),(3,"A2","ENC_B_5V"),(4,"A3","GND"),(5,"A4","GND"),(6,"A5","GND"),(7,"A6","GND"),(8,"A7","GND"),(9,"A8","GND"),
             (10,"GND","GND"),(11,"B8","NC"),(12,"B7","NC"),(13,"B6","NC"),(14,"B5","NC"),(15,"B4","NC"),(16,"B3","NC"),(17,"B2","ENC_B_3V3"),(18,"B1","ENC_A_3V3"),
             (19,"OE","GND"),(20,"VCC","+3V3")]))
A(two("C8", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (30, -36), "+3V3", "GND"))
# ---- hall
A(dict(ref="J9", value="Hall", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(60, -30), rot=0, side="F", pins=[(1,"3V3","+3V3"),(2,"GND","GND"),(3,"SIG","HALL")]))
A(two("R9", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (86, -30), "+3V3", "HALL"))
# ---- body NeoPixel: GP14 -> 74AHCT125 -> 330R -> J10
A(dict(ref="U6", value="74AHCT125", kind="ic_generic", fp="Package_SO:TSSOP-14_4.4x5mm_P0.65mm",
       at=(40, 30), rot=0, side="F",
       pins=[(1,"1OE","GND"),(2,"1A","NEO_3V3"),(3,"1Y","NEO_5V"),(4,"2OE","GND"),(5,"2A","GND"),(6,"2Y","NC"),(7,"GND","GND"),
             (8,"3Y","NC"),(9,"3A","GND"),(10,"3OE","GND"),(11,"4Y","NC"),(12,"4A","GND"),(13,"4OE","GND"),(14,"VCC","+5V_LOGIC")]))
A(two("C9", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (40, 34), "+5V_LOGIC", "GND"))
A(two("R3", "330R", "res", "Resistor_SMD:R_0603_1608Metric", (47, 30), "NEO_5V", "NEO_OUT"))
A(dict(ref="J10", value="Body NeoPixel", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(77, 14), rot=0, side="F", pins=[(1,"5V","+5V_LED"),(2,"GND","GND"),(3,"DATA","NEO_OUT")]))
# ---- slip ring: +5V_LED + GND out to the body-shell NeoPixels only.
#      (The pack charges through its OWN charge lead, routed out through the axle -
#       the board carries no charge path and no charger sense.)
A(dict(ref="J11", value="Slip ring (body lights)", kind="connector", fp="Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical",
       at=(-10, 46), rot=0, side="F", pins=[(1,"5V_LED","+5V_LED"),(2,"GND","GND")]))
# ---- speakers
A(dict(ref="J13", value="SPK L", kind="connector", fp="Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical",
       at=(-40, 30), rot=0, side="F", pins=[(1,"+","SPK_L+"),(2,"-","SPK_L-")]))
A(dict(ref="J14", value="SPK R", kind="connector", fp="Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical",
       at=(-30, 38), rot=0, side="F", pins=[(1,"+","SPK_R+"),(2,"-","SPK_R-")]))
# ---- ESTOP loop
A(dict(ref="J15", value="ESTOP", kind="connector", fp="Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical",
       at=(6, 47), rot=0, side="F", pins=[(1,"LOOP","ESTOP_SENSE"),(2,"GND","GND")]))
A(two("R28", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (-30, 46), "+3V3", "ESTOP_SENSE"))
# ---- I2C expansion (Qwiic-style SH) on both buses
# (I2C-A expansion J16 removed: the ESP32 bus is already exposed on J7 pins 4/5 for the AS5600;
#  J17 on the RP2350 bus is the single expansion port.)
A(dict(ref="J17", value="I2C-B exp (RP2350)", kind="connector", fp="Connector_JST:JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal",
       at=(87, 12), rot=0, side="F", pins=[(1,"GND","GND"),(2,"3V3","+3V3"),(3,"SDA","I2C_B_SDA"),(4,"SCL","I2C_B_SCL")]))
A(two("R5", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (58, -33), "+3V3", "I2C_A_SDA"))
A(two("R6", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (61, -33), "+3V3", "I2C_A_SCL"))
A(two("R7", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (40, 24), "+3V3", "I2C_B_SDA"))
A(two("R8", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (43, 24), "+3V3", "I2C_B_SCL"))
# ---- DFPlayer RX series
A(two("R1", "1k", "res", "Resistor_SMD:R_0603_1608Metric", (74, 12), "DF_TX_RP", "DF_RX_MOD"))
# ---- decoupling near modules
A(two("C10", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (22, 28), "+5V_LOGIC", "GND"))
A(two("C11", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, 15), "+5V_LOGIC", "GND"))
A(two("C12", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (4, 22), "RP_5V", "GND"))
# ---- mounting holes (bosses in the casing) — M3
for i, (x, y) in enumerate([(-42, 24), (-42, -24), (27, 37), (27, -37), (70, 0)], 1):
    A(dict(ref=f"H{i}", value="M3 boss", kind="hole", fp="MountingHole:MountingHole_3.2mm_M3_Pad",
           at=(x, y), rot=0, side="F", pins=[(1, "1", "GND")]))

# board outline: hardware/kicad/board_outline_draft.dxf (origin = axle centre)
AXLE_KEEPOUT_R = 19.0
DEEP_ZONE_R = 42.5

# ---------------------------------------------------------------- board text (silkscreen)
BOARD_TITLE = "Z-DRIVE v10.0  MAINBOARD"
BOARD_TEXT_FRONT = [
    # top-centre open band, above the parts
    (-2, 52.0, 2.4, "Z-DRIVE v10.0"),
]
BOARD_TEXT_BACK = [
    # in the enlarged lower lobe (below every component), mirrored for the back
    (-4, -44, 2.6, "Z-DRIVE v10.0  MAINBOARD"),
    (-4, -48, 1.7, "Design by James VanDusen"),
    (-4, -51, 1.5, "Special thanks to Mimir Reynisson, Greg Bellows and Joe Latiola"),
    (-4, -54, 1.4, "github.com/jlvandusen/Z-ClassControlSystem   -   v10.0 rev A   ${GIT} ${DATE}"),
]
SCH_TITLE = "Z-Drive v10.0 Mainboard"
SCH_COMPANY = "Z-Class Control System - James VanDusen"
SCH_COMMENTS = ["Special thanks to Mimir Reynisson, Greg Bellows and Joe Latiola",
                "Generated from hardware/netlist/mainboard.py - edit the netlist, not this file",
                "Modules: ESP-WROOM-32 DevKitC 30-pin, RP2350-Zero, DFPlayer Mini, Pololu D24V50F5 / D24V25F6, MAX9744 amp module"]

# ---------------------------------------------------------------- rule areas / netclasses
# DevKit antenna end = top of the module (EN / D23 end): no copper on either layer under it.
KEEPOUTS = [  # (x0, y0, x1, y1, name)  KiCad coords, +y up
    (22.5, 19.0, 51.5, 33.5, "ESP32 antenna keep-out - no copper, no pour"),   # top trimmed 36 -> 33.5 so the H3 GND ring (27,37) clears it; still 6 mm beyond the module edge
]
# Trace widths for 2 oz outer copper (IPC-2221, ~10 C rise): 3.0 mm ~ 6 A, 2.0 mm ~ 4.5 A, 1.0 mm ~ 2.6 A
NETCLASSES = [
    # name, clearance, track, via dia, via drill, patterns
    ("Default",  0.15, 0.25, 0.8, 0.4, []),   # PCBWay 4-layer: 0.1 mm capable; 0.15/0.25 leaves margin
    ("Power",    0.25, 1.20, 1.0, 0.5, ["VIN", "BAT*", "+5V_LED", "+6V_SERVO", "AMP_12V*", "RP_5V"]),
    ("Rail",     0.20, 0.60, 0.8, 0.4, ["+5V_LOGIC", "+3V3"]),   # routed as nets; the In2 +5V pour is best-effort on top
    ("Audio",    0.25, 1.00, 1.0, 0.5, ["SPK_*"]),
    ("Motor",    0.25, 0.50, 0.8, 0.4, ["*_PWM", "*_INA", "*_INB", "SERVO_*"]),
]
GND_VIA_PITCH = 0   # stitching vias added post-route (Freerouting adds fanout; a via grid is stamped after import)
