"""
Z-Class v10 mainboard — single source of truth for the KiCad generator.

Each component: ref, value, kind (symbol shape), footprint spec, placement (KiCad mm,
origin = axle centre, +x toward the tail, +y up), and pins: (number, name, net).
Net naming: power rails start with '+', 'GND' is ground, 'NC' = no-connect.
"""

# ---------------------------------------------------------------- modules
DEVKIT_LEFT  = ["EN","VP","VN","D34","D35","D32","D33","D25","D26","D27","D14","D12","D13","GND","VIN"]
DEVKIT_RIGHT = ["D23","D22","TX0","RX0","D21","D19","D18","D5","TX2","RX2","D4","D2","D15","GND","3V3"]  # top=antenna end, bottom=USB end
DEVKIT_NETS = {
    "EN":"NC", "VP":"ESTOP_SENSE", "VN":"CHG_SENSE", "D34":"S2S_POS", "D35":"VBAT_SENSE",
    "D32":"FLY_PWM", "D33":"FLY_INA", "D25":"S2S_PWM", "D26":"S2S_INA", "D27":"S2S_INB",
    "D14":"FLY_INB", "D12":"NC", "D13":"I2C_A_SDA", "GND":"GND", "VIN":"+5V_LOGIC",
    "3V3":"NC", "D15":"I2C_A_SCL", "D2":"NC", "D4":"DRIVE_PWM", "RX2":"DRIVE_INA", "TX2":"DRIVE_INB",
    "D5":"IMU_CS", "D18":"IMU_SCK", "D19":"IMU_MISO", "D21":"LINK_ESP_TX", "RX0":"NC", "TX0":"NC",
    "D22":"LINK_RP_TX", "D23":"IMU_MOSI",
}
ZERO_LEFT   = ["5V","GND","3V3","GP29","GP28","GP27","GP26","GP15","GP14"]
ZERO_RIGHT  = ["GP0","GP1","GP2","GP3","GP4","GP5","GP6","GP7","GP8"]
ZERO_END    = ["GP9","GP10","GP11","GP12","GP13"]
ZERO_NETS = {
    "5V":"RP_5V", "GND":"GND", "3V3":"NC", "GP29":"NC", "GP28":"V5_SENSE", "GP27":"I2C_B_SCL",
    "GP26":"I2C_B_SDA", "GP15":"DF_BUSY", "GP14":"NEO_3V3",
    "GP0":"LINK_RP_TX", "GP1":"LINK_ESP_TX", "GP2":"AMP_SHDN", "GP3":"NC", "GP4":"DF_TX_RP", "GP5":"DF_RX_RP",
    "GP6":"SERVO_L", "GP7":"SERVO_R", "GP8":"DOME_PWM",
    "GP9":"DOME_INA", "GP10":"DOME_INB", "GP11":"ENC_A_3V3", "GP12":"ENC_B_3V3", "GP13":"HALL",
}
DFPLAYER = [  # pin, name, net  (2x8, pin 1 top-left, counter-clockwise like the module)
    (1,"VCC","+5V_LOGIC"), (2,"RX","DF_RX_MOD"), (3,"TX","DF_RX_RP"), (4,"DAC_R","DF_DAC_R"), (5,"DAC_L","DF_DAC_L"),
    (6,"SPK2","NC"), (7,"GND","GND"), (8,"SPK1","NC"), (9,"IO1","NC"), (10,"GND","GND"), (11,"IO2","NC"),
    (12,"ADKEY1","NC"), (13,"ADKEY2","NC"), (14,"USB+","NC"), (15,"USB-","NC"), (16,"BUSY","DF_BUSY"),
]
# Amp as a plug-in module header for rev A (MAX9744 board); rev B integrates the QFN.
AMP_HDR = [(1,"VDD12","AMP_12V"),(2,"GND","GND"),(3,"INL","AMP_INL"),(4,"INR","AMP_INR"),(5,"AGND","GND"),
           (6,"SDA","I2C_B_SDA"),(7,"SCL","I2C_B_SCL"),(8,"SHDN","AMP_SHDN"),
           (9,"OUTL+","SPK_L+"),(10,"OUTL-","SPK_L-"),(11,"OUTR+","SPK_R+"),(12,"OUTR-","SPK_R-")]

def pins_devkit():
    p = []
    for i, n in enumerate(DEVKIT_LEFT, 1):  p.append((i, n, DEVKIT_NETS[n]))
    for i, n in enumerate(DEVKIT_RIGHT, 16): p.append((i, n, DEVKIT_NETS[n]))
    return p

def pins_zero():
    p = []
    for i, n in enumerate(ZERO_LEFT, 1):    p.append((i, n, ZERO_NETS[n]))
    for i, n in enumerate(ZERO_RIGHT, 10):  p.append((i, n, ZERO_NETS[n]))
    for i, n in enumerate(ZERO_END, 19):    p.append((i, n, ZERO_NETS[n]))
    return p

def two(ref, value, kind, fp, at, n1, n2, side="F", rot=0):
    return dict(ref=ref, value=value, kind=kind, fp=fp, at=at, rot=rot, side=side,
                pins=[(1, "1", n1), (2, "2", n2)])

COMPONENTS = []
A = COMPONENTS.append

# ---- MCU modules (custom footprints generated by the tool)
A(dict(ref="U1", value="ESP-WROOM-32 DevKit 30p", kind="module", fp="ZCLASS:DevKit_2x15_25.4mm",
       at=(37, 0), rot=0, side="F", pins=pins_devkit()))
A(dict(ref="U2", value="RP2350-Zero", kind="module", fp="ZCLASS:RP2350_Zero",
       at=(13, 32), rot=0, side="F", pins=pins_zero()))
A(dict(ref="U3", value="DFPlayer Mini", kind="module", fp="ZCLASS:DFPlayer_2x8",
       at=(86, 0), rot=270, side="F", pins=DFPLAYER))
A(dict(ref="J_AMP", value="MAX9744 amp module hdr", kind="connector", fp="ZCLASS:Hdr_2x6",
       at=(-28, 30), rot=0, side="F", pins=AMP_HDR))
# ---- power modules
A(dict(ref="PS1", value="Pololu D24V50F5 5V 5A", kind="module", fp="ZCLASS:Pololu_D24V50F5",
       at=(-30, 4), rot=0, side="F", pins=[(1,"VIN","VIN"),(2,"GND","GND"),(3,"VOUT","+5V_LOGIC"),(4,"EN","NC")]))
A(dict(ref="PS2", value="Pololu D24V22F6 6V 2.5A", kind="module", fp="ZCLASS:Pololu_D24V22F6",
       at=(-34, -20), rot=90, side="F", pins=[(1,"VIN","VIN"),(2,"GND","GND"),(3,"VOUT","+6V_SERVO"),(4,"EN","NC")]))
A(dict(ref="U5", value="AP7361C-33 3.3V LDO", kind="ic3", fp="Package_TO_SOT_SMD:SOT-223-3_TabPin2",
       at=(18, -28), rot=0, side="F", pins=[(1,"GND","GND"),(2,"VOUT","+3V3"),(3,"VIN","+5V_LOGIC")]))
# ---- protection / input
A(dict(ref="J1", value="XT60PW", kind="connector", fp="ZCLASS:XT60PW",
       at=(-27, -31), rot=0, side="F", pins=[(1,"+","BAT+"),(2,"-","GND")]))
A(dict(ref="F1", value="10A blade fuse", kind="fuse", fp="ZCLASS:Fuse_Mini_Blade",
       at=(-13, -26.5), rot=0, side="F", pins=[(1,"1","BAT+"),(2,"2","BAT_F")]))
A(dict(ref="Q1", value="SQJ431EP P-FET RPP", kind="ic3", fp="Package_SO:PowerPAK_SO-8_Single",
       at=(-1, -26), rot=0, side="F", pins=[(1,"S","BAT_F"),(2,"D","VIN"),(3,"G","GND")]))
A(two("D1", "SMBJ15A", "diode", "Diode_SMD:D_SMB", (8, -22.5), "VIN", "GND"))
A(two("C1", "220u/25V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-32, -19), "VIN", "GND"))
A(two("R24", "47k", "res", "Resistor_SMD:R_0603_1608Metric", (44, 44), "VIN", "VBAT_SENSE"))
A(two("R25", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (44, 41), "VBAT_SENSE", "GND"))
# ---- 5V / 3V3 rail parts
A(two("C2", "470u/10V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-26, -19), "+5V_LOGIC", "GND"))
A(two("C3", "1000u/10V", "cap", "Capacitor_SMD:CP_Elec_10x10", (-22, -20), "+5V_LED", "GND"))
A(two("F3", "3A polyfuse", "fuse", "Fuse:Fuse_1812_4532Metric", (-44, -18), "+5V_LOGIC", "+5V_LED"))
A(two("C4", "470u/10V", "cap", "Capacitor_SMD:CP_Elec_8x10", (-20, -20), "+6V_SERVO", "GND"))
A(two("D2", "SS14", "diode", "Diode_SMD:D_SMA", (0, 48), "+5V_LOGIC", "RP_5V"))
A(two("C5", "10u", "cap", "Capacitor_SMD:C_1206_3216Metric", (-1, -30.8), "+5V_LOGIC", "GND"))
A(two("C6", "10u", "cap", "Capacitor_SMD:C_1206_3216Metric", (24, -31), "+3V3", "GND"))
A(two("R29", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (22, 48), "+5V_LOGIC", "V5_SENSE"))
A(two("R30", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (25, 48), "V5_SENSE", "GND"))
# ---- amp supply
A(two("F4", "3A fuse", "fuse", "Fuse:Fuse_1206_3216Metric", (56, 24), "VIN", "AMP_12V_F"))
A(two("L1", "FB 600R 3A", "res", "Inductor_SMD:L_1206_3216Metric", (60, 24), "AMP_12V_F", "AMP_12V"))
A(two("C7", "1000u/25V", "cap", "Capacitor_SMD:CP_Elec_10x10", (62, 14), "AMP_12V", "GND"))
A(two("C26", "1u", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, -12), "DF_DAC_L", "AMP_INL"))
A(two("C27", "1u", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, -15), "DF_DAC_R", "AMP_INR"))
# ---- motor driver headers (keyed 2x5): VCC PWM INA INB GND / VCC PWM INA INB GND
def motor_hdr(ref, at, chA, chB):
    pa, ia, ib = chA; pb, ja, jb = chB
    return dict(ref=ref, value="DFR0601 ribbon 2x5", kind="connector", fp="ZCLASS:Hdr_2x5_shrouded",
                at=at, rot=0, side="F",
                pins=[(1,"VCC","+3V3"),(3,"PWM1",pa),(5,"INA1",ia),(7,"INB1",ib),(9,"GND","GND"),
                      (2,"VCC","+3V3"),(4,"PWM2",pb),(6,"INA2",ja),(8,"INB2",jb),(10,"GND","GND")])
A(motor_hdr("J2", (-8, -41), ("DRIVE_PWM","DRIVE_INA","DRIVE_INB"), ("S2S_PWM","S2S_INA","S2S_INB")))
A(motor_hdr("J3", (13, -41),  ("FLY_PWM","FLY_INA","FLY_INB"),     ("DOME_PWM","DOME_INA","DOME_INB")))
# pull-downs on every driver input
for i, net in enumerate(["DRIVE_PWM","DRIVE_INA","DRIVE_INB","S2S_PWM","S2S_INA","S2S_INB",
                         "FLY_PWM","FLY_INA","FLY_INB","DOME_PWM","DOME_INA","DOME_INB"]):
    A(two(f"R{12+i}", "10k", "res", "Resistor_SMD:R_0603_1608Metric", ((-17 + i*3) if i < 6 else (4 + (i-6)*3), -33.5), net, "GND"))
# ---- servos
A(dict(ref="J4", value="Servo L", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(55, 21), rot=0, side="F", pins=[(1,"SIG","SERVO_L"),(2,"6V","+6V_SERVO"),(3,"GND","GND")]))
A(dict(ref="J5", value="Servo R", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(66, 19), rot=0, side="F", pins=[(1,"SIG","SERVO_R"),(2,"6V","+6V_SERVO"),(3,"GND","GND")]))
# ---- IMU (SPI)
A(dict(ref="J6", value="IMU BMI160 SPI", kind="connector", fp="Connector_JST:JST_SH_SM06B-SRSS-TB_1x06-1MP_P1.00mm_Horizontal",
       at=(57, -24), rot=0, side="F",
       pins=[(1,"3V3","+3V3"),(2,"GND","GND"),(3,"SCK","IMU_SCK_R"),(4,"MISO","IMU_MISO"),(5,"MOSI","IMU_MOSI_R"),(6,"CS","IMU_CS")]))
A(two("R31", "33R", "res", "Resistor_SMD:R_0603_1608Metric", (50, -26), "IMU_SCK", "IMU_SCK_R"))
A(two("R32", "33R", "res", "Resistor_SMD:R_0603_1608Metric", (50, -23), "IMU_MOSI", "IMU_MOSI_R"))
# ---- S2S sensor (AS5600 or pot): 3V3 GND OUT SDA SCL
A(dict(ref="J7", value="S2S AS5600/pot", kind="connector", fp="Connector_JST:JST_XH_B5B-XH-A_1x05_P2.50mm_Vertical",
       at=(70, -19), rot=0, side="F",
       pins=[(1,"3V3","+3V3"),(2,"GND","GND"),(3,"OUT","S2S_OUT"),(4,"SDA","I2C_A_SDA"),(5,"SCL","I2C_A_SCL")]))
A(two("R2", "1k", "res", "Resistor_SMD:R_0603_1608Metric", (64, -30), "S2S_OUT", "S2S_POS"))
A(two("C28", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (67, -30), "S2S_POS", "GND"))
# ---- dome encoder (5V) -> 74LVC245 -> 3V3
A(dict(ref="J8", value="Dome encoder", kind="connector", fp="Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical",
       at=(82, -14), rot=0, side="F", pins=[(1,"5V","+5V_LOGIC"),(2,"GND","GND"),(3,"A","ENC_A_5V"),(4,"B","ENC_B_5V")]))
A(dict(ref="U7", value="74LVC245A", kind="ic_generic", fp="Package_SO:TSSOP-20_4.4x6.5mm_P0.65mm",
       at=(30, -32), rot=0, side="F",
       pins=[(1,"DIR","GND"),(2,"A1","ENC_A_5V"),(3,"A2","ENC_B_5V"),(4,"A3","NC"),(5,"A4","NC"),(6,"A5","NC"),(7,"A6","NC"),(8,"A7","NC"),(9,"A8","NC"),
             (10,"GND","GND"),(11,"B8","NC"),(12,"B7","NC"),(13,"B6","NC"),(14,"B5","NC"),(15,"B4","NC"),(16,"B3","NC"),(17,"B2","ENC_B_3V3"),(18,"B1","ENC_A_3V3"),
             (19,"OE","GND"),(20,"VCC","+3V3")]))
A(two("C8", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (30, -36), "+3V3", "GND"))
# ---- hall
A(dict(ref="J9", value="Hall", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(60, -30), rot=0, side="F", pins=[(1,"3V3","+3V3"),(2,"GND","GND"),(3,"SIG","HALL")]))
A(two("R9", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (86, -30), "+3V3", "HALL"))
# ---- body NeoPixel: GP14 -> 74AHCT125 -> 330R -> J10
A(dict(ref="U6", value="74AHCT125", kind="ic_generic", fp="Package_SO:TSSOP-14_4.4x5mm_P0.65mm",
       at=(40, 30), rot=0, side="F",
       pins=[(1,"1OE","GND"),(2,"1A","NEO_3V3"),(3,"1Y","NEO_5V"),(4,"2OE","GND"),(5,"2A","GND"),(6,"2Y","NC"),(7,"GND","GND"),
             (8,"3Y","NC"),(9,"3A","GND"),(10,"3OE","GND"),(11,"4Y","NC"),(12,"4A","GND"),(13,"4OE","GND"),(14,"VCC","+5V_LOGIC")]))
A(two("C9", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (40, 34), "+5V_LOGIC", "GND"))
A(two("R3", "330R", "res", "Resistor_SMD:R_0603_1608Metric", (47, 30), "NEO_5V", "NEO_OUT"))
A(dict(ref="J10", value="Body NeoPixel", kind="connector", fp="Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical",
       at=(77, 14), rot=0, side="F", pins=[(1,"5V","+5V_LED"),(2,"GND","GND"),(3,"DATA","NEO_OUT")]))
# ---- slip ring: 5V_LED GND CHG+ CHG-   +  charger pass-through XT30 + sense
A(dict(ref="J11", value="Slip ring", kind="connector", fp="Connector_JST:JST_VH_B4P-VH_1x04_P3.96mm_Vertical",
       at=(-10, 46), rot=0, side="F", pins=[(1,"5V_LED","+5V_LED"),(2,"GND","GND"),(3,"CHG+","CHG+"),(4,"CHG-","CHG-")]))
A(two("F2", "3A fuse", "fuse", "Fuse:Fuse_1206_3216Metric", (-40, 18), "CHG+", "CHG_F"))
A(dict(ref="J12", value="Charger XT30", kind="connector", fp="ZCLASS:XT30PW",
       at=(-46, 8), rot=90, side="F", pins=[(1,"+","CHG_F"),(2,"-","CHG-")]))
A(two("R26", "47k", "res", "Resistor_SMD:R_0603_1608Metric", (-36, 18), "CHG+", "CHG_SENSE"))
A(two("R27", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (-36, 21), "CHG_SENSE", "GND"))
# ---- speakers
A(dict(ref="J13", value="SPK L", kind="connector", fp="Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical",
       at=(-40, 30), rot=0, side="F", pins=[(1,"+","SPK_L+"),(2,"-","SPK_L-")]))
A(dict(ref="J14", value="SPK R", kind="connector", fp="Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical",
       at=(-30, 38), rot=0, side="F", pins=[(1,"+","SPK_R+"),(2,"-","SPK_R-")]))
# ---- ESTOP loop
A(dict(ref="J15", value="ESTOP", kind="connector", fp="Connector_JST:JST_XH_B2B-XH-A_1x02_P2.50mm_Vertical",
       at=(6, 47), rot=0, side="F", pins=[(1,"LOOP","ESTOP_SENSE"),(2,"GND","GND")]))
A(two("R28", "10k", "res", "Resistor_SMD:R_0603_1608Metric", (-30, 46), "+3V3", "ESTOP_SENSE"))
# ---- I2C expansion (Qwiic-style SH) on both buses
A(dict(ref="J16", value="I2C-A exp (ESP32)", kind="connector", fp="Connector_JST:JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal",
       at=(66, -28), rot=0, side="F", pins=[(1,"GND","GND"),(2,"3V3","+3V3"),(3,"SDA","I2C_A_SDA"),(4,"SCL","I2C_A_SCL")]))
A(dict(ref="J17", value="I2C-B exp (RP2350)", kind="connector", fp="Connector_JST:JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal",
       at=(87, 12), rot=0, side="F", pins=[(1,"GND","GND"),(2,"3V3","+3V3"),(3,"SDA","I2C_B_SDA"),(4,"SCL","I2C_B_SCL")]))
A(two("R5", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (92, -12), "+3V3", "I2C_A_SDA"))
A(two("R6", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (92, -15), "+3V3", "I2C_A_SCL"))
A(two("R7", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (92, 12), "+3V3", "I2C_B_SDA"))
A(two("R8", "4.7k", "res", "Resistor_SMD:R_0603_1608Metric", (92, 15), "+3V3", "I2C_B_SCL"))
# ---- DFPlayer RX series
A(two("R1", "1k", "res", "Resistor_SMD:R_0603_1608Metric", (74, 12), "DF_TX_RP", "DF_RX_MOD"))
# ---- decoupling near modules
A(two("C10", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (22, 28), "+5V_LOGIC", "GND"))
A(two("C11", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (74, 15), "+5V_LOGIC", "GND"))
A(two("C12", "100n", "cap", "Capacitor_SMD:C_0603_1608Metric", (4, 22), "RP_5V", "GND"))
# ---- mounting holes (bosses in the casing) — M3
for i, (x, y) in enumerate([(-42, 24), (-42, -24), (27, 37), (27, -37), (70, 0)], 1):
    A(dict(ref=f"H{i}", value="M3 boss", kind="hole", fp="MountingHole:MountingHole_3.2mm_M3_Pad",
           at=(x, y), rot=0, side="F", pins=[(1, "1", "GND")]))

# board outline: hardware/kicad/board_outline_draft.dxf (origin = axle centre)
AXLE_KEEPOUT_R = 19.0
DEEP_ZONE_R = 42.5

# ---------------------------------------------------------------- board text (silkscreen)
BOARD_TITLE = "Z-DRIVE v10.0  MAINBOARD"
BOARD_TEXT_FRONT = [
    # (x, y, size_mm, text)   KiCad coords (origin = axle centre, +y up)
    (0, 48.0, 2.0, "Z-DRIVE v10.0"),
    (0, 44.5, 1.2, "Z-Class Control System"),
]
BOARD_TEXT_BACK = [
    # below the axle hole: x -20..20 between the bore (y -19) and the motor headers (y -36) is pad-free
    (0, -24, 2.6, "Z-DRIVE v10.0 MAINBOARD"),
    (0, -28, 1.6, "Design by James VanDusen"),
    (0, -31.5, 1.4, "Special thanks to Mimir Reynisson, Greg Bellows and Joe Latiola"),
    # tail, between the DevKit and the DFPlayer rows
    (0, -34.3, 1.15, "github.com/jlvandusen/Z-ClassControlSystem"),
    (63.5, -12, 1.0, "rev A ${GIT} ${DATE}"),
]
SCH_TITLE = "Z-Drive v10.0 Mainboard"
SCH_COMPANY = "Z-Class Control System - James VanDusen"
SCH_COMMENTS = ["Special thanks to Mimir Reynisson, Greg Bellows and Joe Latiola",
                "Generated from hardware/netlist/mainboard.py - edit the netlist, not this file",
                "Modules: ESP-WROOM-32 DevKit, RP2350-Zero, DFPlayer Mini, Pololu D24V50F5 / D24V22F6, MAX9744 amp module"]

# ---------------------------------------------------------------- rule areas / netclasses
# DevKit antenna end = top of the module (EN / D23 end): no copper on either layer under it.
KEEPOUTS = [  # (x0, y0, x1, y1, name)  KiCad coords, +y up
    (22.5, 19.0, 51.5, 36.0, "ESP32 antenna keep-out - no copper, no pour"),
]
# Trace widths for 2 oz outer copper (IPC-2221, ~10 C rise): 3.0 mm ~ 6 A, 2.0 mm ~ 4.5 A, 1.0 mm ~ 2.6 A
NETCLASSES = [
    # name, clearance, track, via dia, via drill, patterns
    ("Default",  0.20, 0.30, 0.8, 0.4, []),
    ("Power",    0.30, 3.00, 1.6, 0.8, ["VIN", "BAT*", "+5V_LOGIC", "+5V_LED", "+6V_SERVO", "AMP_12V*", "CHG*", "RP_5V"]),
    ("Audio",    0.25, 1.00, 1.0, 0.5, ["SPK_*"]),
    ("Motor",    0.25, 0.50, 0.8, 0.4, ["*_PWM", "*_INA", "*_INB", "SERVO_*"]),
]
GND_VIA_PITCH = 9.0   # mm stitching grid
