"""Generate firmware/ESP32_DOME_RC4/PsiEnvelopes.h from the BB-8 sound set.

For every MP3/NNNN.mp3 the script decodes the audio (ffmpeg), computes a 25 Hz
amplitude envelope (40 ms RMS windows), gates the noise floor, normalizes each
track to its own peak, applies a perceptual gamma, and emits uint8 tables the
dome firmware plays back in sync with the track (the drive relays the track
number in the psi field). Re-run whenever the sound set changes:

    python tools/gen_psi_envelopes.py "C:\\Users\\james\\Downloads\\bb8_mp3\\MP3"
"""
import os, re, subprocess, sys, struct, datetime

SRC = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\james\Downloads\bb8_mp3\MP3"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "firmware", "ESP32_DOME_RC4", "PsiEnvelopes.h")
STEP_MS = 40          # 25 Hz
RATE = 8000           # decode rate
WIN = RATE * STEP_MS // 1000
GAMMA = 0.6           # perceptual lift for quiet passages
GATE = 0.06           # fraction of track peak treated as silence

tracks = {}
for f in sorted(os.listdir(SRC)):
    m = re.fullmatch(r"(\d{4})\.mp3", f, re.IGNORECASE)
    if not m:
        continue
    n = int(m.group(1))
    if not (1 <= n <= 119):
        continue
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", os.path.join(SRC, f),
         "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"],
        capture_output=True).stdout
    samples = struct.unpack(f"<{len(raw)//2}h", raw)
    env = []
    for i in range(0, len(samples) - WIN, WIN):
        w = samples[i:i + WIN]
        rms = (sum(s * s for s in w) / WIN) ** 0.5
        env.append(rms)
    if not env:
        continue
    peak = max(env) or 1.0
    q = []
    for v in env:
        x = v / peak
        x = 0.0 if x < GATE else x
        q.append(round(255 * (x ** GAMMA)))
    # trim trailing silence
    while q and q[-1] == 0:
        q.pop()
    tracks[n] = q
    print(f"  {n:4d}: {len(q)*STEP_MS/1000:6.1f}s  {len(q):4d} steps  peak-normalized")

total = sum(len(v) for v in tracks.values())
with open(OUT, "w", encoding="utf-8", newline="\n") as h:
    h.write(f"""#pragma once
// Auto-generated by tools/gen_psi_envelopes.py on {datetime.date.today()} - DO NOT EDIT.
// 25 Hz amplitude envelopes (uint8) for every MP3/NNNN.mp3 in the sound set.
// The dome plays the envelope for the track number relayed in the psi field,
// so the PSI flickers with the actual beeps. {len(tracks)} tracks, {total} bytes.
#include <stdint.h>

#define PSI_ENV_STEP_MS {STEP_MS}

struct PsiEnv {{ uint8_t track; uint16_t len; const uint8_t *data; }};

""")
    for n, q in tracks.items():
        h.write(f"static const uint8_t psiEnv_{n}[] = {{")
        for i, v in enumerate(q):
            if i % 24 == 0:
                h.write("\n  ")
            h.write(f"{v},")
        h.write("\n};\n")
    h.write("\nstatic const PsiEnv PSI_ENVS[] = {\n")
    for n, q in tracks.items():
        h.write(f"  {{ {n}, {len(q)}, psiEnv_{n} }},\n")
    h.write("};\n")
    h.write(f"static const uint8_t PSI_ENV_COUNT = {len(tracks)};\n\n")
    h.write("""static inline const PsiEnv* psiEnvFor(uint8_t track) {
  for (uint8_t i = 0; i < PSI_ENV_COUNT; i++)
    if (PSI_ENVS[i].track == track) return &PSI_ENVS[i];
  return nullptr;
}
""")
print(f"wrote {OUT}: {len(tracks)} tracks, {total} envelope bytes")
